-- Insert sample blog articles
INSERT INTO articles (
  title,
  slug, 
  excerpt,
  content,
  author_name,
  category,
  tags,
  cover_image,
  published_at,
  read_time_minutes,
  featured,
  status,
  seo_title,
  seo_description
) VALUES 
(
  'The Ultimate South Asian Wedding Planning Guide',
  'ultimate-south-asian-wedding-planning-guide',
  'A comprehensive guide to planning your perfect South Asian wedding, covering traditions, budget, and modern touches.',
  '<h2>Planning Your Dream South Asian Wedding</h2><p>Planning a South Asian wedding is both exciting and overwhelming. With rich traditions, elaborate ceremonies, and countless details to coordinate, having a structured approach is essential.</p><h3>Pre-Wedding Ceremonies</h3><p>From engagement ceremonies to mehendi and sangeet, each pre-wedding event has its own significance and requirements. Start planning these 6-8 months in advance.</p><h3>Budget Planning</h3><p>South Asian weddings can be expensive, but with proper planning, you can create a beautiful celebration within your budget. Allocate 40% to venue and catering, 20% to photography, and 15% to attire.</p><h3>Vendor Selection</h3><p>Choose vendors who understand South Asian traditions and customs. This includes photographers who know key moments to capture and caterers familiar with authentic cuisine.</p>',
  'Priya Sharma',
  'Planning',
  ARRAY['wedding planning', 'south asian', 'traditions', 'budget'],
  'https://images.unsplash.com/photo-1583939003579-730e3918a45a?w=800&h=600&fit=crop',
  NOW() - INTERVAL '2 days',
  8,
  true,
  'published',
  'Ultimate South Asian Wedding Planning Guide – Mēl Milaap',
  'Complete guide to planning your perfect South Asian wedding. Tips on traditions, budget, vendors, and creating your dream celebration.'
),
(
  'Finding Love in the Digital Age: Modern Matchmaking Tips',
  'finding-love-digital-age-modern-matchmaking',
  'How modern technology is revolutionizing traditional matchmaking while preserving cultural values and family involvement.',
  '<h2>The Evolution of Matchmaking</h2><p>Traditional matchmaking has evolved significantly with technology, but the core values remain the same - finding compatible life partners with similar backgrounds and values.</p><h3>Creating an Authentic Profile</h3><p>Your profile is your first impression. Be honest about your interests, values, and what you''re looking for. Include recent photos that represent your personality.</p><h3>The Role of Family</h3><p>Modern matchmaking still values family input. Involve your family in the process while maintaining your autonomy in making the final decision.</p>',
  'Rajesh Patel',
  'Relationships',
  ARRAY['matchmaking', 'relationships', 'online dating', 'family'],
  'https://images.unsplash.com/photo-1522673607200-164d1b6ce486?w=800&h=600&fit=crop',
  NOW() - INTERVAL '5 days',
  6,
  true,
  'published',
  'Modern Matchmaking Tips for Finding Love – Mēl Milaap',
  'Discover how technology is revolutionizing traditional matchmaking while preserving cultural values in the digital age.'
),
(
  'Preserving Traditions: Incorporating Heritage into Modern Weddings',
  'preserving-traditions-heritage-modern-weddings',
  'Learn how to beautifully blend traditional South Asian customs with contemporary wedding styles for a celebration that honors your heritage.',
  '<h2>Honoring Your Heritage</h2><p>Modern couples are finding creative ways to honor their cultural heritage while adding contemporary touches to their weddings.</p><h3>Traditional Ceremonies</h3><p>Consider which traditional ceremonies are most important to you and your families. You don''t have to include every ritual - choose those that hold special meaning.</p><h3>Modern Touches</h3><p>Incorporate modern elements like playlist mixing traditional and contemporary music, fusion cuisine, or contemporary decor with traditional colors.</p>',
  'Meera Singh',
  'Traditions',
  ARRAY['traditions', 'heritage', 'modern wedding', 'cultural'],
  'https://images.unsplash.com/photo-1520854221256-17451cc331bf?w=800&h=600&fit=crop',
  NOW() - INTERVAL '1 week',
  5,
  true,
  'published',
  'Preserving Heritage in Modern Weddings – Mēl Milaap',
  'Learn to beautifully blend traditional South Asian customs with contemporary wedding styles for a meaningful celebration.'
),
(
  'Wedding Photography: Capturing Every Sacred Moment',
  'wedding-photography-capturing-sacred-moments',
  'Essential tips for choosing the right photographer and ensuring every precious moment of your South Asian wedding is beautifully captured.',
  '<h2>Choosing Your Wedding Photographer</h2><p>Your wedding photographer will preserve the memories of your special day for generations. Choose someone who understands South Asian traditions and can capture both intimate moments and grand celebrations.</p><h3>Pre-Wedding Consultation</h3><p>Discuss your expectations, must-have shots, and traditional ceremonies. Share your timeline so they can plan accordingly.</p><h3>Key Moments to Capture</h3><p>From the groom''s baraat to the seven vows, ensure your photographer knows which traditional moments are essential for your family.</p>',
  'Arjun Photography',
  'Tips',
  ARRAY['photography', 'wedding tips', 'memories', 'traditions'],
  'https://images.unsplash.com/photo-1511285560929-80b456fea0bc?w=800&h=600&fit=crop',
  NOW() - INTERVAL '10 days',
  4,
  false,
  'published',
  'Wedding Photography Tips for South Asian Celebrations – Mēl Milaap',
  'Essential guide to choosing the right photographer and capturing every sacred moment of your South Asian wedding.'
),
(
  'Love Story: From Melbourne to Marriage',
  'love-story-melbourne-to-marriage',
  'Read the heartwarming love story of Kavya and Rohan, who met through Mēl Milaap and planned their dream wedding in Melbourne.',
  '<h2>A Match Made in Melbourne</h2><p>Kavya was a doctor in Melbourne, and Rohan was an engineer in Sydney. Despite the distance, their connection through Mēl Milaap was instant.</p><h3>The First Meeting</h3><p>After weeks of messaging, they decided to meet halfway in Canberra. What was supposed to be a quick coffee turned into a day-long conversation.</p><h3>The Proposal</h3><p>Rohan proposed during Diwali at the Royal Botanic Gardens in Melbourne, surrounded by families from both sides who had traveled to witness the moment.</p><h3>The Wedding</h3><p>Their three-day celebration in Melbourne perfectly blended Tamil and Gujarati traditions, creating new memories while honoring their heritage.</p>',
  'Mēl Milaap Team',
  'Real Stories',
  ARRAY['love story', 'success story', 'melbourne', 'real couples'],
  'https://images.unsplash.com/photo-1606216794074-735e91aa2c92?w=800&h=600&fit=crop',
  NOW() - INTERVAL '3 days',
  7,
  false,
  'published',
  'Love Story: From Melbourne to Marriage – Mēl Milaap Success',
  'Heartwarming love story of Kavya and Rohan who met through Mēl Milaap and planned their dream wedding in Melbourne.'
);