// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mywzsikpdauqtyhrtres.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im15d3pzaWtwZGF1cXR5aHJ0cmVzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwNDkzNjUsImV4cCI6MjA3MjYyNTM2NX0.rXpGujcisTnPCAbMuSEX55dej2DplMrrd0g1ws5HcG4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});